<style type="text/css">.entry-edit .entry-edit-head { background: #EC145A!important;padding: 5px 10px!important; }.content-header { margin-bottom: 0px !important; }</style>
<div style="overflow: hidden;">
<h2><span style="font-family: Yekan;" class="kavenegarapiadmin-menu">
  <img style="vertical-align: middle;" src="<?php echo $this->getSkinUrl('images/kavenegarapi/kavenegarapi_header.png'); ?>">
  وب سرویس پیام کوتاه کاوه نگار</span>
</h2>
</div>